fmod VHDL-IODEF-MOD is

  protecting STRING .

  sorts IODef IOType IOValues .

  ops in out : -> IOType [ctor] .
  ops "std_logic" : -> IOValues [ctor] .
  op _:__; : String IOType IOValues -> IODef [ctor] .

endfm

view IODef from TRIV to VHDL-IODEF-MOD is
  sort Elt to IODef .
endv

fmod VHDL-INSTCOLON-MOD is

  protecting VHDL-IODEF-MOD .
  ***protecting STRING .
  protecting LIST{IODef} .

  sorts Inst InstColon Architecture Port .
  subsorts Architecture Port < Inst .

  op _; : Inst -> InstColon [ctor].

  *** Instruction ops declarations (no dependency on instruction lists)
  *** - Test nop
  op nop : -> Inst [ctor] .
  *** - Port
  op port (_) : NeList{IODef} -> Port [ctor] .

endfm

view InstColon from TRIV to VHDL-INSTCOLON-MOD is
  sort Elt to InstColon .
endv

fmod VHDL-VALUE-MOD is

  protecting INT .
  protecting STRING .

  sort StdLogic Value .
  subsorts Int StdLogic < Value .

  ops '0' '1' 'U' 'X' 'Z' 'W' 'L' 'H' '-' : -> StdLogic [ctor] .

endfm

view Value from TRIV to VHDL-VALUE-MOD is
  sort Elt to Value .
endv

mod VHDLMOD is
  *** RAFAEL MORALES PALACIOS - SEMANTICS OF VHDL IN MAUDE
  
  *** IMPORT DATATYPE MODULES TO BE USED
  protecting NAT .
  ***protecting INT .
  ***protecting STRING .
  protecting VHDL-INSTCOLON-MOD .
  protecting VHDL-VALUE-MOD .
  protecting MAP{String, Value} .
  protecting LIST{InstColon} .
  
  *** Declare sorts to be used and hierarchy between them.
  sorts VHDLSim Code Signal SignalName Var Const VarConstName Process Clock ScheduledInst Und Error Entity . ***sorts VHDLSim Code Entity Port Signal SignalName Var Const VarConstName Value Architecture Process Clock ScheduledInst Und Error .
  sorts EmptyList InstBlock StructuredInstList . ***sorts Inst EmptyList NeList{Inst} List{Inst} InstBlock StructuredInstList .
  sorts NeScheduleList ScheduleList NeListeningList ListeningList .
  sorts Assign SignalAssign VarConstAssign .
  sorts Store NeStore SignalStore VarStore ConstStore .
  sorts EmptyStore NeSignalStore NeVarStore NeConstStore .


  *** Simulator components
  *** subsorts Code Clock ScheduleList ListeningList SignalStore VarStore ConstStore < VHDLSim .
  
  subsorts VarStore ConstStore < Map{String, Value} .
  subsorts SignalStore < Map{String, Value} .
  ***subsorts NeSignalStore NeVarStore NeConstStore < NeStore .
  ***subsorts EmptyStore NeSignalStore < SignalStore .
  ***subsorts EmptyStore NeVarStore < VarStore .
  ***subsorts EmptyStore NeConstStore < ConstStore .
  ***subsorts SignalAssign VarConstAssign < Assign .
  ***subsorts SignalAssign < NeSignalStore .
  ***subsorts VarConstAssign < NeVarStore NeConstStore .
  ***
  ***subsorts Int StdLogic < Value .

  subsorts String < SignalName VarConstName .

  subsorts List{InstColon} StructuredInstList < Code .

  subsorts ScheduledInst < NeScheduleList .
  subsorts EmptyList NeScheduleList < ScheduleList .
  subsorts SignalName < NeListeningList .
  subsorts EmptyList NeListeningList < ListeningList .

  subsorts Entity < Inst .

  ***subsorts Entity Architecture Port < Inst .

  op und : -> Und [ctor] .
  op EmptyList : -> EmptyList [ctor] .
  op error : String -> Error [ctor] .



  *** Code represents a whole VHDL file. Rules will be needed for each code statement/block
  op <_|_><_|_><<_|_|_>> : Clock Code ScheduleList ListeningList SignalStore VarStore ConstStore -> VHDLSim [ctor] .

  *** Stores definition
  *** Maybe make a joint definition?? This will probably raise a parse error
  ***op [_<-_] : SignalName Value -> SignalAssign [ctor] .
  ***op [_<-_] : VarConstName Value -> VarConstAssign [ctor] .
  ***op [_<-_] : String Value -> Assign [ctor] .

  ***op EmptyStore : -> Store [ctor] .
  *** TODO: maybe join all store types
  ***op __ : SignalAssign SignalStore -> NeSignalStore [assoc comm ctor id: EmptyStore] .
  ***op __ : VarConstAssign VarStore -> NeVarStore [assoc comm ctor id: EmptyStore] .
  ***op __ : VarConstAssign ConstStore -> NeConstStore [assoc comm ctor id: EmptyStore] .


  *** Instruction ops declarations (that include inner instruction lists)
  *** - Entity
  op entity _ is _ end _ : String List{InstColon} String -> Entity [ctor] .
  
  *** lookup: auxiliar op to lookup values from signal store
  op lookup : Map{String, Value} String -> Value .
  op lookup-sg : Map{String, Value} String -> Value .

  op _[_] : List{InstColon} List{InstColon} -> StructuredInstList [ctor].


  *** final_state: final state reachable when max time elapsed is reached
  *** op final_state : VHDLSim -> FinalState .


  *** Variable definition

  vars I1 S1 : InstColon .
  vars SignalId : SignalName .
  var Val : Value .
  var IL IL1 IL2 : List{InstColon} .
  var NeIL1 NeIL2 : NeList{InstColon} .
  var SgSTR : Map{String, Value} .
  var STR VarSTR ConstSTR : Map{String, Value} .
  var Int1 Int2 : Int .
  var Str : String .
  var Clk : Clock .
  var SchList : ScheduleList .
  var LstList : ListeningList .

  *** Store is a Set
  ***eq [Str <- Val][Str <- Val] = [Str <- Val] .



  *** Rules
  rl [entity] : < Clk | (entity Str is IL1 end Str) ; IL2 >< SchList | LstList ><< SgSTR | VarSTR | ConstSTR >> => < Clk | IL1 [IL2] >< SchList | LstList ><< SgSTR | VarSTR | ConstSTR >> .

  *** lookup rule: get value from reference from local store
  rl [lookup] : lookup(STR, Str) => STR[Str] .
  rl [lookup-sg] : lookup-sg(SgSTR, Str) => SgSTR[Str] .

  *** nop: test instruction
  rl [nop] : < Clk | nop ; IL2 >< SchList | LstList ><< SgSTR | VarSTR | ConstSTR >> => < Clk | IL2 >< SchList | LstList ><< SgSTR | VarSTR | ConstSTR >> .



  *** List{Inst} operations 
  op head : NeList{InstColon} -> InstColon .
  eq head(I1 IL) = I1 .

  op tail : NeList{InstColon} -> List{InstColon} .
  eq tail(I1 IL) = IL .



endm

