fmod VHDL-IODEF-MOD is

  protecting STRING .

  sorts IODef IOType IOValues SgDesc .

  ops in out inout : -> IOType [ctor] .
  ops "std_logic" "bit" : -> IOValues [ctor] .

  op (_$_) : IOType IOValues -> SgDesc [ctor] .

  op _:__; : String IOType IOValues -> IODef [ctor] .

endfm

view IODef from TRIV to VHDL-IODEF-MOD is
  sort Elt to IODef .
endv

view SgDesc from TRIV to VHDL-IODEF-MOD is
  sort Elt to SgDesc .
endv

fmod VHDL-VALUE-MOD is

  protecting RAT .
  protecting STRING .
  protecting VHDL-IODEF-MOD .

  sorts StdLogic Value IntVal StdLogicVal TimeVal NatVal .
  sorts Time TimeUnit TimeDelta Delta Bit .
  subsorts NatVal IntVal StdLogicVal TimeVal < Value . *** checkear. añadir un wrapper a los tipos
  subsorts Bit < StdLogic < StdLogicVal .
  subsorts TimeDelta < Time .

  ***subsorts Int < IntVal .
  ***subsorts StdLogic < Value .

  op intVal : Int -> IntVal [ctor] .
  op stdlogicVal : StdLogic -> StdLogicVal [ctor] .
  op timeVal : Time -> TimeVal [ctor] .
  op natVal : Nat -> NatVal [ctor] .


  *** Bit logic

  ops '0' '1' : -> Bit [ctor] .
  ops 'U' 'X' 'Z' 'W' 'L' 'H' '-' : -> StdLogic [ctor] .

  *** Time

  ops hr min sec ms us ns ps fs : -> TimeUnit [ctor] .
  op __ : Rat TimeUnit -> Time [ctor] .

  *** operations will be done with ns
  op to-ns : Time -> Time [ctor] .

  var R : Rat .
  eq to-ns(R fs) = to-ns((R / 1000) ps).
  eq to-ns(R ps) = to-ns((R / 1000) ns).
  eq to-ns(R ns) = R ns .
  eq to-ns(R us) = to-ns((R * 1000) ns).
  eq to-ns(R ms) = to-ns((R * 1000 ) us) .
  eq to-ns(R sec) = to-ns((R * 1000) ms) .
  eq to-ns(R min) = to-ns((R * 60) sec) .
  eq to-ns(R hr) = to-ns((R * 60) min) .

  *** Delta delays
  op delta : Nat -> Delta [ctor] .
  op delta : -> Delta [ctor] .
  eq delta = delta(1) .
  op _ + _ : Time Delta -> TimeDelta [ctor] .

  op _+_ : Delta Delta -> Delta [assoc comm ctor] .

  vars TDelta1 TDelta2 : Delta .
  var T : Time .
  vars N1 N2 : Nat .
  eq delta(N1) + delta(N2) = delta(N1 + N2) .
  eq (T + TDelta1) + TDelta2 = T + (TDelta1 + TDelta2) .

  op default : IOValues -> Value .
  eq default("std_logic") = 'U' .
  eq default("bit") = '0' .

endfm

view Value from TRIV to VHDL-VALUE-MOD is
  sort Elt to Value .
endv


fmod VHDL-GENERIC-MOD is

  protecting STRING .
  protecting VHDL-VALUE-MOD .

  sorts GenDef VarType .

  op _: _ := _; : String VarType Value -> GenDef [ctor] .
  ops natural integer time positive : -> VarType [ctor] .

endfm

view GenDef from TRIV to VHDL-GENERIC-MOD is
  sort Elt to GenDef .
endv

fmod VHDL-INSTCOLON-MOD is

  protecting VHDL-IODEF-MOD .
  protecting VHDL-VALUE-MOD .
  protecting VHDL-GENERIC-MOD .
  protecting LIST{IODef} .
  protecting LIST{GenDef} .
  

  sorts Inst InstColon EntityInst EntityInstColon Port SignalName VarConstName SgDecl SgAssign AExp Term Op Generic .
  subsorts Port Generic < EntityInst .
  subsorts EntityInst SgDecl SgAssign < Inst .
  *** The following order causes Advisory messages on loading the module
  ***subsorts EntityInstColon < InstColon .
  subsorts String < SignalName VarConstName .
  subsorts Int StdLogicVal < AExp .

  ops and or xand sg-xor : -> Op [ctor] . 
  ***op _ _ _ : Term Op AExp -> AExp [ctor] .

  vars Op : Op .
  vars SignalId : SignalName .
  var EntityI : EntityInst .
  ***vars T : Term .
  ***eq T Op 'U' = 'U' .

  op _; : Inst -> InstColon [ctor].
  ***mb (EntityI ;) : EntityInstColon .
  ***op _; : EntityInst -> EntityInstColon [ctor] .

  *** Instruction ops declarations (no dependency on instruction lists)
  *** - Test nop
  op nop : -> Inst [ctor] .
  *** - Port
  op port (_) : NeList{IODef} -> Port [ctor] .
  *** - Generic
  op generic (_) : NeList{GenDef} -> Generic [ctor] .

  vars StdLogicVal1 : StdLogicVal .
  vars AExp1 AExp2 : AExp .
  op ___ : AExp Op AExp -> AExp [ctor] .

  op not_ : AExp -> AExp [ctor] .
  ceq not AExp1 = stdlogicVal('0') if AExp1 == stdlogicVal('1') .
  ceq not AExp1 = stdlogicVal('1') if AExp1 == stdlogicVal('0') .
  ceq not AExp1 = stdlogicVal('U') if AExp1 == stdlogicVal('U') .
  ***op _or_ : StdLogic AExp -> AExp [ctor] .
  eq stdlogicVal('1') or AExp1 = stdlogicVal('1') .
  eq stdlogicVal('0') or AExp1 = AExp1 .
  eq stdlogicVal('U') or AExp1 = AExp1 .
  ***op _and_ : StdLogic AExp -> AExp [ctor] .
  eq stdlogicVal('1') and AExp1 = AExp1 .
  eq stdlogicVal('0') and AExp1 =  stdlogicVal('0') .
  eq stdlogicVal('U') and AExp1 = stdlogicVal('U') .
  op _xor_ : AExp AExp -> AExp [ditto ctor] .
  ceq AExp1 xor AExp2 = stdlogicVal('1') if AExp1 =/= AExp2 /\ (AExp1 == stdlogicVal('1') or AExp2 == stdlogicVal('1')) .
  eq AExp1 xor AExp2 =  stdlogicVal('0') [owise] .
  ***op _xand_ : AExp AExp -> AExp [ctor] .
  ceq AExp1 xand AExp2 = stdlogicVal('1') if AExp1 == AExp2 .
  eq AExp1 xand AExp2 =  stdlogicVal('0') [owise] .

  ceq StdLogicVal1 sg-xor AExp2 = stdlogicVal('1') if StdLogicVal1 =/= AExp2 /\ (StdLogicVal1 == stdlogicVal('1') or AExp2 == stdlogicVal('1')) .
  eq StdLogicVal1 sg-xor AExp2 =  stdlogicVal('0') [owise] .

  op _ <= _ : SignalName AExp -> SgAssign [ctor] .

  op solve : AExp -> StdLogicVal .
  eq solve(StdLogicVal1) = StdLogicVal1 .
  eq solve(not AExp1) = not solve(AExp1) .
  eq solve(AExp1 or AExp2) = solve(AExp1) or solve(AExp2) .
  eq solve(AExp1 and AExp2) = solve(AExp1) and solve(AExp2) .
  eq solve(AExp1 xor AExp2) = solve(AExp1) xor solve(AExp2) .
  eq solve(AExp1 xand AExp2) = solve(AExp1) xand solve(AExp2) .

endfm

view InstColon from TRIV to VHDL-INSTCOLON-MOD is
  sort Elt to InstColon .
endv

view EntityInstColon from TRIV to VHDL-INSTCOLON-MOD is
  sort Elt to EntityInstColon .
endv

view SignalName from TRIV to VHDL-INSTCOLON-MOD is
  sort Elt to SignalName .
endv

fmod VHDL-SCHEDULE-MOD is

  protecting VHDL-VALUE-MOD .
  protecting VHDL-INSTCOLON-MOD .

  sorts ScheduledInst SgTimeTuple Transaction SignalState .

  *** An ScheduledInst contains the instruction to be executed and the delay
  *** TODO: check if it would be more accurate to just delay an assignment (delay,sg,value)
  op {scheduledInst: time _, inst _} : Time InstColon -> ScheduledInst [ctor] .

  *** Transactions (ScheduledEvents) relate time and value for a certain signal
  op {sgName _, value _} : SignalName Value -> SignalState [ctor] .
  op {scheduledEvent: time _, args _} : Time SignalState -> Transaction [ctor] .

  op {sgName _, time _} : SignalName Time -> SgTimeTuple [ctor] .

endfm

view ScheduledInst from TRIV to VHDL-SCHEDULE-MOD is
  sort Elt to ScheduledInst .
endv

view SgTimeTuple from TRIV to VHDL-SCHEDULE-MOD is
  sort Elt to SgTimeTuple .
endv

view Transaction from TRIV to VHDL-SCHEDULE-MOD is
  sort Elt to Transaction .
endv

mod VHDLMOD is
  *** RAFAEL MORALES PALACIOS - SEMANTICS OF VHDL IN MAUDE
  
  *** IMPORT DATATYPE MODULES TO BE USED
  protecting NAT .
  ***protecting INT .
  ***protecting STRING .
  protecting VHDL-INSTCOLON-MOD .
  protecting VHDL-VALUE-MOD .
  protecting VHDL-GENERIC-MOD .
  protecting MAP{String, Value} .
  protecting MAP{SgTimeTuple, Value} .
  protecting MAP{String, SgDesc} .
  protecting LIST{InstColon} .
  protecting LIST{EntityInstColon} .
  protecting LIST{SignalName} .
  protecting LIST{ScheduledInst} .
  protecting LIST{Transaction} .
  
  *** Declare sorts to be used and hierarchy between them.
  sorts VHDLSim Parser ParserTime ParserInsts Code Signal Var Const Clock SimClock ClockPrev Und Error Entity Architecture SgDescStore TimeControlSection ValueStores DescStores . ***sorts VHDLSim Code Entity Port Signal SignalName Var Const VarConstName Value Architecture Process Clock ScheduledInst Und Error .
  sorts Process ProcessSensitivity ProcessNoSensitivity .
  sorts EmptyList InstBlock StructuredInstList . ***sorts Inst EmptyList NeList{Inst} List{Inst} InstBlock StructuredInstList .
  sorts EventSchList .
  sorts NeScheduleList ScheduleList NeListeningList ListeningList .
  sorts Assign SignalAssign VarConstAssign .
  sorts Stores NeStore SignalStore VarStore ConstStore .
  sorts EmptyStore NeSignalStore NeVarStore NeConstStore .


  *** Simulator components
  subsorts Code < VHDLSim .
  
  ***subsorts VarStore ConstStore < Map{String, Value} .
  ***subsorts SignalStore < Map{SgTimeTuple, Value} .
  ***subsorts SgDescStore < Map{String, SgDesc} .
  ***subsorts NeSignalStore NeVarStore NeConstStore < NeStore .
  ***subsorts EmptyStore NeSignalStore < SignalStore .
  ***subsorts EmptyStore NeVarStore < VarStore .
  ***subsorts EmptyStore NeConstStore < ConstStore .
  ***subsorts SignalAssign VarConstAssign < Assign .
  ***subsorts SignalAssign < NeSignalStore .
  ***subsorts VarConstAssign < NeVarStore NeConstStore .
  ***
  ***subsorts Int StdLogic < Value .

  subsorts List{InstColon} StructuredInstList < Code .

  ***subsorts ScheduledInst < NeScheduleList .
  ***subsorts EmptyList NeScheduleList < ScheduleList .
  ***subsorts SignalName < NeListeningList .
  ***subsorts EmptyList NeListeningList < ListeningList .
  subsorts ListeningList < List{SignalName} .
  subsorts ScheduleList < List{ScheduledInst} .
  subsorts EventSchList < List{Transaction} .

  subsorts ProcessSensitivity ProcessNoSensitivity < Process .
  subsorts Entity Architecture Process Error < Inst .

  ***subsorts Entity Architecture Port < Inst .

  op und : -> Und [ctor] .
  op EmptyList : -> EmptyList [ctor] .
  op error : String -> Error [ctor] .

  op _||_||_ : ScheduleList ListeningList EventSchList -> TimeControlSection [ctor] .
  op << _ | _ | _ >> : Map{SgTimeTuple, Value} Map{String, Value} Map{String, Value} -> ValueStores [ctor] .
  op < _ > : Map{String, SgDesc} -> DescStores [ctor] .

  op _ # _ : ValueStores DescStores -> Stores [ctor] .

  op [_->_] : List{InstColon} List{ScheduledInst} -> ParserInsts [ctor] .

  op _ _ : ParserInsts Stores -> Parser [ctor] .
  op _ < events: _ > : Parser EventSchList -> ParserTime [ctor] .

  *** Code represents a whole VHDL file. Rules will be needed for each code statement/block
  op <_|_><_>_ : SimClock List{InstColon} TimeControlSection Stores -> VHDLSim [ctor] .

  op clk : Time -> Clock [ctor] .
  op [prev: _] : Clock -> ClockPrev [ctor] .
  op _ _ : Clock ClockPrev -> SimClock [ctor] .

  *** Stores definition
  *** Maybe make a joint definition?? This will probably raise a parse error
  ***op [_<-_] : SignalName Value -> SignalAssign [ctor] .
  ***op [_<-_] : VarConstName Value -> VarConstAssign [ctor] .
  ***op [_<-_] : String Value -> Assign [ctor] .

  ***op EmptyStore : -> Store [ctor] .
  *** TODO: maybe join all store types
  ***op __ : SignalAssign SignalStore -> NeSignalStore [assoc comm ctor id: EmptyStore] .
  ***op __ : VarConstAssign VarStore -> NeVarStore [assoc comm ctor id: EmptyStore] .
  ***op __ : VarConstAssign ConstStore -> NeConstStore [assoc comm ctor id: EmptyStore] .


  *** Instruction ops declarations (that include inner instruction lists)
  
  *** - Entity
  op entity _ is _ end _ : String List{InstColon} String -> Entity [ctor] .
  op entity _ is end _ : String String -> Entity [ctor] .
  
  *** - Architecture
  op architecture _ of _ is _ begin _ end _ : String String List{InstColon} List{InstColon} String -> Architecture [ctor] .
  
  *** - Process
  *** TODO: Variable assignment possibility before begin not included
  op process _ begin _ end process : List{SignalName} List{InstColon} -> ProcessSensitivity [ctor] .
  op process begin _ end process : List{InstColon} -> ProcessNoSensitivity [ctor] .
  op end process : -> Inst [ctor] .


  *** - Signal (declaration)
  op signal _:_ : NeList{SignalName} IOValues -> SgDecl [ctor] .


  *** lookup: auxiliar op to lookup values from signal store
  op lookup : Map{String, Value} String -> Value .
  *** lookup-sg must be an eq to be able to evaluate it everywhere
  op lookup-sg : Map{SgTimeTuple, Value} SgTimeTuple -> StdLogicVal .


  ***op _[_] : List{InstColon} List{InstColon} -> StructuredInstList [ctor].


  *** final_state: final state reachable when max time elapsed is reached
  *** op final_state : VHDLSim -> FinalState .


  *** Variable definition

  vars I1 S1 : InstColon .
  vars SignalId SignalId1 SignalId2 : SignalName .
  var Val : Value .
  var IL IL1 IL2 : List{InstColon} .
  var NeIL1 NeIL2 : NeList{InstColon} .
  var SgSTR : Map{SgTimeTuple, Value} .
  var SgTimeTuple : SgTimeTuple .
  var STR VarSTR ConstSTR : Map{String, Value} .
  var SgDescSTR : Map{String, SgDesc} .
  var SgDesc : SgDesc .
  var Int1 Int2 : Int .
  var Str Str2 : String .
  var Clk : SimClock .
  var ClkP1 ClkP2 : Clock .
  var N : Nat .
  var NVal : NatVal .
  var Int : Int .
  var IntVal : IntVal .
  var SchList : List{ScheduledInst} .
  var EventSchList : List{Transaction} .
  var LstList : List{SignalName} .
  var NeIODefL : NeList{IODef} .
  var IODef : IODef .
  var IOType : IOType .
  var IOValues : IOValues .
  var IODefL : List{IODef} .
  var StdLogicVal : StdLogicVal .
  var AExp1 : AExp .
  var Error : Error .
  vars Op : Op .
  var VarType : VarType .
  var NeGenDefL : NeList{GenDef} .
  var GenDefL : List{GenDef} .
  var EntityIL : List{EntityInstColon} .
  vars T Tprev Tnext : Time .
  var ClockPrev : ClockPrev .
  var TVal : TimeVal .
  var NzN : NzNat .
  var NeSgNameL : NeList{SignalName} .
  var SgNameL : List{SignalName} .
  var TControlSect : TimeControlSection .
  var ValStores : ValueStores .
  var SignalState : SignalState .
  var StoresVar : Stores .
  var DescStores : DescStores .

  *** Workflow: run(IL, EventSchList) -> Parse -> insitSimArch -> Simulation Loop
  op run : List{InstColon} List{Transaction} -> VHDLSim [ctor] .
  eq run(IL, EventSchList) = initSimArch(parse(IL) < events: EventSchList >) .

  op parse : List{InstColon} -> Parser [ctor] .
  eq parse(IL) = [ IL -> nil ] << empty | empty | empty >> # < empty > .

  op initSimArch : ParserTime -> VHDLSim [ctor] .
  eq initSimArch([ nil -> SchList ] << SgSTR | VarSTR | ConstSTR >> # < SgDescSTR > < events: EventSchList >) = < clk(0 ns) [prev: clk(0 ns)] | nil >< SchList || nil || EventSchList > << insertDefault(SgDescSTR, SgSTR) | VarSTR | ConstSTR >> # < SgDescSTR > .

  op insertDefault : Map{String, SgDesc} Map{SgTimeTuple, Value} -> Map{SgTimeTuple, Value} .
  eq insertDefault(SignalId |-> ( IOType $ IOValues ), SgSTR) = insert({sgName SignalId, time 0 ns}, default(IOValues),  SgSTR) .
  eq insertDefault((SignalId |-> ( IOType $ IOValues ), SgDescSTR), SgSTR) = insert({sgName SignalId, time 0 ns}, default(IOValues),  insertDefault(SgDescSTR, SgSTR)) .

  ***op initSim : List{InstColon} List{Transaction} -> VHDLSim [ctor] .
  ***eq initSim(IL, EventSchList) = < clk(0 ns) [prev: clk(0 ns)] | IL >< nil | nil | EventSchList > << empty | empty | empty >> # < empty > .

  *** An entity declared without instructions is equivalent to an entity with an empty list of instructions
  eq entity Str is end Str = entity Str is nil end Str .
  *** A process declared without a sensitivity list is equal to the process with an empty sensitivity list 
  eq process begin IL end process = process nil begin IL end process .

  *** TODO: Restrict values of SgSTR to StdLogic with cmb

  ***_:__; : String IOType IOValues

  *** Rules

  *** Non-deterministic change of signal values
  ***rl [nd-sg-val-change] : ({sgName SignalId, time T} |-> StdLogicVal , SgSTR) => insert({sgName SignalId, time T}, not StdLogicVal, SgSTR) .

  ***rl [entity] : < Clk | (entity Str is IL1 end Str) ; IL >< TControlSect > ValStores # DescStores 
  ***              => 
  ***              < Clk | IL1 exit-block(IL) >< TControlSect > ValStores # DescStores .
  rl [parse-entity] : [ (entity Str is IL1 end Str) ; IL -> SchList ]
                      => 
                      [ IL1 exit-block(IL) -> SchList ] .
  
  ***rl [entity-noIL] : < Clk | (entity Str is end Str) ; IL >< TControlSect > ValStores # DescStores 
  ***            => 
  ***            < Clk | IL >< TControlSect > ValStores # DescStores .
  ***crl [entity-err] : < Clk | (entity Str is IL1 end Str2) ; IL >< TControlSect > ValStores => error("ERROR: Entity name mismatch") if Str =/= Str2 .

  ***rl [port] : < Clk | (port(NeIODefL)) ; IL >< TControlSect > ValStores # DescStores 
  ***            => 
  ***            < Clk | get-port-sg(NeIODefL) ; exit-block(IL) >< TControlSect > ValStores # DescStores .
  rl [parse-port] : [ (port(NeIODefL)) ; IL -> SchList ]
                    => 
                    [ get-port-sg(NeIODefL) ; exit-block(IL) -> SchList ] .
  rl [parse-get-port-sg] : [ (get-port-sg((Str : IOType IOValues ;) IODefL)) ; exit-block(IL) -> SchList ] ValStores # < SgDescSTR > 
                     => 
                     [ get-port-sg(IODefL) ; exit-block(IL) -> SchList ] ValStores # < insert(Str, ( IOType $ IOValues), SgDescSTR) > .
  ***-----
  ***rl [get-port-sg-empty] : < Clk | (get-port-sg(nil)) ; exit-block(IL) >< TControlSect > ValStores # DescStores => < Clk | exit-block(IL) >< TControlSect > ValStores # DescStores .
  ***rl [get-port-sg] : < Clk | (get-port-sg((Str : IOType IOValues ;) IODefL)) ; exit-block(IL) >< TControlSect > ValStores # DescStores 
  ***                   => 
  ***                   < Clk | get-port-sg(IODefL) ; exit-block(IL) >< TControlSect > ValStores # < insert(Str, ( IOType $ IOValues), SgDescSTR) > .
  ***rl [generic] : < Clk | (generic(NeGenDefL)) ; IL >< TControlSect > ValStores # DescStores 
  ***               => 
  ***              < Clk | get-gen(NeGenDefL) ; exit-block(IL) >< TControlSect > ValStores # DescStores .
  ***rl [get-gen] : < Clk | (get-gen((Str : VarType := Val ;) GenDefL)) ; exit-block(IL) >< TControlSect > << SgSTR | VarSTR | ConstSTR >> # DescStores 
  ***             =>
  ***             < Clk | verify-gen(VarType, Val) ; get-gen(GenDefL) ; exit-block(IL) >< TControlSect > << SgSTR | VarSTR | insert(Str, Val, ConstSTR) >> # DescStores .
  
  rl [parse-generic] : [ (generic(NeGenDefL)) ; IL -> SchList ]
                => 
                [ get-gen(NeGenDefL) ; exit-block(IL) -> SchList ] .
  crl [parse-get-gen] : [ (get-gen((Str : VarType := Val ;) GenDefL)) ; exit-block(IL) -> SchList ] << SgSTR | VarSTR | ConstSTR >> # DescStores
                =>
                [ get-gen(GenDefL) ; exit-block(IL) -> SchList ] << SgSTR | VarSTR | insert(Str, Val, ConstSTR) >> # DescStores 
                if verify-gen(VarType, Val) .
  ***rl [signal] : < Clk | (signal NeSgNameL : IOValues) ; IL >< TControlSect > ValStores # DescStores 
  ***              => 
  ***              < Clk | decl-sg(NeSgNameL, IOValues) ; exit-block(IL) >< TControlSect > ValStores # DescStores .
  rl [parse-signal] : [ (signal NeSgNameL : IOValues) ; IL -> SchList ]
                => 
                [ decl-sg(NeSgNameL, IOValues) ; exit-block(IL) -> SchList ] .
  ***rl [decl-sg] : < Clk | decl-sg(SignalId SgNameL, IOValues) ; exit-block(IL) >< TControlSect > ValStores # DescStores 
  ***              =>
  ***              < Clk | decl-sg(SgNameL, IOValues) ; exit-block(IL) >< TControlSect > ValStores # < insert(SignalId, ( inout $ IOValues), SgDescSTR) > .
  rl [parse-decl-sg] : [ decl-sg(SignalId SgNameL, IOValues) ; exit-block(IL) -> SchList ] ValStores # < SgDescSTR >
                =>
                [ decl-sg(SgNameL, IOValues) ; exit-block(IL) -> SchList ] ValStores # < insert(SignalId, ( inout $ IOValues), SgDescSTR) > .
  
  ***rl [architecture] : < Clk | (architecture Str of Str2 is IL1 begin IL2 end Str) ; IL >< TControlSect > ValStores # DescStores 
  ***                    => 
  ***                    < Clk | IL1 exit-block(IL2 exit-block(IL)) >< TControlSect > ValStores # DescStores .
  rl [parse-architecture] : [ (architecture Str of Str2 is IL1 begin IL2 end Str) ; IL -> SchList ] StoresVar
                          => 
                          [ IL1 exit-block(IL2 exit-block(IL)) -> SchList ] StoresVar .  

  *** assign-sg-val : assign a value to a signal after solving all AExp and signal lookups
  crl [assign-sg-val-sch] : < clk(T) [prev: clk(Tprev)] | nil >< {scheduledInst: time T, inst (SignalId <= solve(AExp1)) ;}  SchList || LstList || EventSchList > << SgSTR | VarSTR | ConstSTR >> # < SgDescSTR > 
                      => 
                      < clk(T) [prev: clk(Tprev)] | nil >< SchList || LstList || EventSchList > << insert({sgName SignalId, time T + delta}, solve(AExp1), SgSTR) | VarSTR | ConstSTR >> # < SgDescSTR >
                      if sg-val-changed(SignalId, solve(AExp1), Tprev, SgSTR) .

  rl [parse-assign-sg-val] : [ (SignalId <= AExp1) ; IL -> SchList ] StoresVar
                            => 
                            [ IL -> SchList {scheduledInst: time 0 ns, inst (SignalId <= AExp1) ;} ] StoresVar .
                            ***if verify-sg(out, SignalId, SgDescSTR) .
  
  *** TODO: Make LstList so that it can have SgNameL [LstList] to keep track of nested processes' LstLists?
  crl [process] : < clk(T) ClockPrev | nil >< {scheduledInst: time T, inst (process SgNameL begin IL2 end process) ;}  SchList || LstList || EventSchList > << SgSTR | VarSTR | ConstSTR >> # DescStores 
                => 
                < clk(T) ClockPrev | nil >< unfoldProcess(IL2, T) SchList || SgNameL LstList || EventSchList > << SgSTR | VarSTR | ConstSTR >> # DescStores 
                if processSensitivityActivate(clk(T) ClockPrev, SgNameL, SgSTR) .
  rl [parse-process] : [ (process SgNameL begin IL2 end process) ; IL -> SchList ]
                    => 
                    [ IL -> SchList {scheduledInst: time 0 ns, inst (process SgNameL begin IL2 end process) ;} ] .
  ***rl [process-NoSensitivity] : < Clk | (process begin IL2 end process) ; IL >< TControlSect > ValStores # DescStores 
  ***            => 
  ***            < Clk | IL2 end process ; exit-block(IL) >< TControlSect > ValStores # DescStores .
  
  ***rl [parse-end-process] : < Clk | end process ; exit-block(IL) >< SchList || LstList || EventSchList > ValStores # DescStores
  ***                  => 
  ***                  < Clk | exit-block(IL) >< SchList || nil || EventSchList > ValStores # DescStores .

  ***rl [end-parse] : [ nil -> SchList ] StoresVar < events: EventSchList >
  ***                =>
  ***                initSimArch([ nil -> SchList ] StoresVar < events: EventSchList >) .

  *** TODO: Modify so that the schedule list is repeated for T+delta if the state of the variables has changed
  ***       - Consider having this checked in advance, so that it does not have to be executed N+1 times to check the state is mantained?? 
  ***       - Add condition to let time advance when T is 0 ns
  crl [end-sim-cycle-delta] : < clk(T) [prev: clk(Tprev)] | nil >< {scheduledInst: time Tnext, inst I1 } SchList || LstList || EventSchList > << SgSTR | VarSTR | ConstSTR >> # DescStores
                            => 
                            < clk(Tnext) [prev: clk(T)] | nil >< {scheduledInst: time Tnext, inst I1 } SchList || nil || EventSchList > << SgSTR | VarSTR | ConstSTR >> # DescStores 
                            if T =/= Tnext .
    
  
  rl [lookup-sg] :  < ClkP1 [prev: clk(T)] | (SignalId <= SignalId1 Op AExp1) ; IL >< TControlSect > << SgSTR | VarSTR | ConstSTR >> # DescStores 
                  => 
                  < ClkP1 [prev: clk(T)] | (SignalId <= lookup-sg(SgSTR, {sgName SignalId1, time T}) Op AExp1) ; IL >< TControlSect > << SgSTR | VarSTR | ConstSTR >> # DescStores .
                  
  rl [lookup-sg-bis] :  < ClkP1 [prev: clk(T)] | (SignalId <= AExp1 Op SignalId1) ; IL >< TControlSect > << SgSTR | VarSTR | ConstSTR >> # DescStores 
                => 
                < ClkP1 [prev: clk(T)] | (SignalId <= AExp1 Op lookup-sg(SgSTR, {sgName SignalId1, time T})) ; IL >< TControlSect > << SgSTR | VarSTR | ConstSTR >> # DescStores .
  
  ***rl [solve-aexp] : SignalId Op AExp1 => lookup(SignalId)
  
  *** lookup rule: get value from reference from local store
  rl [lookup] : lookup(STR, Str) => STR[Str] .
  ***rl [lookup-sg] : lookup-sg(SignalId) => SgSTR[SignalId] .

  *** nop: test instruction
  rl [nop] : nop ; IL => IL .


  *** exit-block: exit an inner block and continue where left before
  rl [exit-block] : < Clk | exit-block(IL) >< TControlSect > ValStores # DescStores 
                    => 
                    < Clk | IL >< TControlSect > ValStores # DescStores .
  
  rl [parse-exit-block] : [ exit-block(IL) -> SchList ]
                => 
                [ IL -> SchList ] .

  rl [error] : < Clk | Error ; IL >< TControlSect > ValStores # DescStores => Error ; .

  *** List{Inst} operations 
  op head : NeList{InstColon} -> InstColon .
  eq head(I1 IL) = I1 .

  op tail : NeList{InstColon} -> List{InstColon} .
  eq tail(I1 IL) = IL .

  op exit-block : List{InstColon} -> List{InstColon} .
  ***eq exit-block(IL) = IL .

  op get-port-sg : List{IODef} -> Inst [ctor] .
  eq get-port-sg(nil) = nop .

  op get-sgtype : SgDesc -> IOType .
  eq get-sgtype(IOType $ IOValues) = IOType .

  op get-gen : List{GenDef} -> Inst [ctor] .
  eq get-gen(nil) = nop .

  op decl-sg : List{SignalName} IOValues -> Inst [ctor] .
  eq decl-sg(nil, IOValues) = nop .

  op unfoldProcess : List{InstColon} Time -> List{ScheduledInst} [ctor] .
  eq unfoldProcess(nil, T) = nil .
  eq unfoldProcess(I1 IL, T) = {scheduledInst: time T, inst I1} unfoldProcess(IL, T) .

  op processSensitivityActivate : SimClock List{SignalName} Map{SgTimeTuple, Value} -> Bool .
  eq processSensitivityActivate(Clk, nil, SgSTR) = true .
  ceq processSensitivityActivate(clk(T) [prev: clk(Tprev)], SignalId1 SgNameL, SgSTR) = true 
                                                                                if lookup-sg(SgSTR, {sgName SignalId1, time T}) =/= lookup-sg(SgSTR, {sgName SignalId1, time Tprev}) 
                                                                                    or processSensitivityActivate(clk(T) [prev: clk(Tprev)], SgNameL, SgSTR) .
  eq processSensitivityActivate(clk(T) [prev: clk(Tprev)], SignalId1 SgNameL, SgSTR) = false [owise] .

  op sg-val-changed : SignalName StdLogicVal Time Map{SgTimeTuple, Value} -> Bool .
  ceq sg-val-changed(SignalId, StdLogicVal, Tprev, SgSTR) = true if StdLogicVal =/= lookup-sg(SgSTR, {sgName SignalId, time Tprev}) .
  eq sg-val-changed(SignalId, StdLogicVal, Tprev, SgSTR) = false [owise] .


  *** ------------

  op ___ : SignalName Op AExp -> AExp [ctor] .
  ***eq SignalId Op AExp1 = lookup-sg(SignalId, SgSTR) Op AExp1 .
  op ___ : AExp Op SignalName -> AExp [ctor] .
  ***eq AExp1 Op SignalId = AExp1 Op lookup-sg(SignalId, SgSTR) .
  op ___ : SignalName Op SignalName -> AExp [ctor] .
  ***eq SignalId1 Op SignalId2 = lookup-sg(SignalId1) Op lookup-sg(SignalId2, SgSTR) .

  *** Needed specific declaration for xor due to collisions
  op _xor_ : SignalName AExp -> AExp [ctor] .
  op _xor_ : AExp SignalName -> AExp [ctor] .
  ***eq SignalId xor AExp1 = lookup-sg(SignalId, SgSTR) xor AExp1 .
  eq SignalId xor AExp1 = SignalId sg-xor AExp1 .
  eq AExp1 xor SignalId = AExp1 sg-xor SignalId .
  ***op _xor_ : AExp SignalName -> AExp [ctor] .
  ***eq AExp1 xor SignalId = AExp1 xor lookup-sg(SignalId) .
  
  *** lookup signal from signal store
  eq lookup-sg(SgSTR, SgTimeTuple) = SgSTR[SgTimeTuple] .

  ***--------------------------
  *** VERIFICATION
  ***--------------------------
  *** verify-sg: auxilar op to verify signal types on instructions
  op verify-sg : IOType SignalName Map{String, SgDesc} -> Bool [ctor] .
  ceq verify-sg(IOType, SignalId, SgDescSTR) = true if IOType == get-sgtype(SgDescSTR[SignalId]) .
  eq verify-sg(IOType, SignalId, SgDescSTR) = false [owise] .
  
  *** verify-gen : auxiliar op to verify generic declaration types
  op verify-gen : VarType Value -> Bool [ctor] .
  eq verify-gen(natural, NVal) = true .
  eq verify-gen(integer, IntVal) = true .
  eq verify-gen(time, TVal) = true .
  eq verify-gen(positive, NzN) = true .
  eq verify-gen(VarType, Val) = false [owise] .

endm

